# Site wide configuration

title:            Pere Villega
locale:           en_GB
url:  http://perevillega.com           


# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false


# Site owner
owner:
  name: Pere Villega
  avatar: bio-photo.png
  bio: "If at first you don’t succeed; call it version 1.0"
  email: pere.villega@gmail.com
  disqus-shortname: 
  twitter: pvillega
  facebook: pvillega
  google:
    plus: PereVillega
    analytics: UA-32390320-1
    verify: bkCiO-bEhrfzDurtD6X772P1JroB8Q_Hb_I_AVSXqIE
    ad-client: 
    ad-slot: 
  bing-verify: A144448522476B8417CB74945AA3E085
  github: pvillega
  stackoverflow: 116791/pere-villega
  linkedin: perevillega
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]
